### PR TITLE
Format titles for images and links

### PR DESCRIPTION
**Pull request by mfix-stripe**
PTAL @rpaul-stripe

### CODE REVIEW

**Review by matv-stripe — APPROVED** [review]

**Comment by duncanma-stripe** [comment]
This looks a little odd, given that it has a Link and an image, but both using the image format (starting with a !), instead of 

```
[Link](/href "title")
![Alt](/image "title")
```

right? (I know it is just testing the formatter, but still )

**Comment by mfix-stripe** [comment]
> This looks a little odd, given that it has a Link and an image, but both using the image format (starting with a !), instead of
> 
> ```
> [Link](/href "title")
> Alt
> ```
> 
> right? (I know it is just testing the formatter, but still )

First one is a link, second one is an image. I must be misunderstanding something @duncanma-stripe 🙂

**Comment by matv-stripe** [comment]
@mfix-stripe 

in your diff, both of the examples are images (they both start with `!`)

**Comment by mfix-stripe** [comment]
> @mfix-stripe
> 
> in your diff, both of the examples are images (they both start with `!`)

I see now! Yeah that was a typo. Fixing now.

**Pull request merged**
