### PR TITLE
Add parent getter

### PR DESCRIPTION
**Pull request by mfix-stripe**
Cc @segphault 
Cc @bibek-stripe

### CODE REVIEW

**Comment by segphault** [comment]
I'm leaning towards no on this change, but I'd like to hear more about the problem that you're looking to solve with it before I make a decision. 

We generally discourage users from implementing behaviors in transforms that rely on a node's parentage. This makes it easier to operate on subsets of the tree and avoids a bunch of problems that can arise from copying and moving nodes around during transform steps. There are, of course, a bunch of valid reasons why you might want to do this for static analysis outside of a transform.

Are you aware of the [`walkWithParents`](https://github.com/markdoc/markdoc/blob/7bbb0b39e829fd028f1a295d2a33cfd38bc5015e/src/validator.ts#L297-L304) function that is used for this in validation? I'm wondering if it is sufficient for what you are trying to do here. I'm open to maybe exposing that as a top-level export.

**Comment by mfix-stripe** [comment]
> Are you aware of the [`walkWithParents`](https://github.com/markdoc/markdoc/blob/7bbb0b39e829fd028f1a295d2a33cfd38bc5015e/src/validator.ts#L297-L304) function that is used for this in validation? I'm wondering if it is sufficient for what you are trying to do here. I'm open to maybe exposing that as a top-level export.

Was not aware of this! @bibek-stripe were you? This would solve your use case right?

**Comment by bibek-stripe** [comment]
My use case is that I'd like to validate that a `card` tag is only rendered as a child of `card-group`. In other words, a document with contents

```
{% card-group %}
{% card %}Foo{% /card %}
{% /card-group %}
```

is valid but

```
{% card %}Foo{% /card %}
```

should surface an error.

I'm currently doing this validation all the way up at the `document` node and walking the entirety of the document AST to check for all instances of this which is actually working quite well for my use case.

I wasn't aware of the `walkWithParents` method. It looks like it's only importable from `@markdoc/markdoc/dist/src/validator` so probably not safe to import right? Also, how would one use it for a use case like mine?

**Comment by segphault** [comment]
Ah! If you are using this only in validation, that is already supported. In a validation function, the property `config.validation.parents` has an array with all of the parents of the current node. I wrote a [blog post](https://seg.phault.net/blog/2024/04/accessing-parent-nodes-in-a-markdoc-validation-function/) that demonstrates how to use it with a similar use case to the one you describe. 

You want to do something like this in your validation function: `config.validation.parents.some(parent => parent.tag === 'card-group')`

**Comment by bibek-stripe** [comment]
Oh sweet! Would be cool to have this in the docs at markdoc.dev as well! :)

**Comment by mfix-stripe** [comment]
> Oh sweet! Would be cool to have this in the docs at markdoc.dev as well! :)

@bibek-stripe feel free to add it and I can review

**Pull request closed without merging**
