### PR TITLE
Add validation for functions existing

### LINKED ISSUE #123: No error when accessing missing variables
I see the same happens when accessing missing variables, isn't this expected to throw an error?

_Originally posted by @ntgussoni in https://github.com/markdoc/markdoc/issues/122#issuecomment-1185614546_

### PR DESCRIPTION
**Pull request by mfix-stripe**
Closes #123

PTAL @rpaul-stripe

### CODE REVIEW

**Comment by rpaul-stripe** [comment]
In the Stripe documentation, we compute the variables that we pass into the Markdoc environment per request because many of the values are specific to the individual user. That means we don't have the variables available in any of the places where we perform validation internally (CI or our VSCode extension). We would expect `config.variables` to be undefined in those environments and don't want that to be treated as an error.  

Maybe we could make it so that variable validation only occurs if `config.variables` exists?

**Comment by mfix-stripe** [comment]
> In the Stripe documentation, we compute the variables that we pass into the Markdoc environment per request because many of the values are specific to the individual user. That means we don't have the variables available in any of the places where we perform validation internally (CI or our VSCode extension). We would expect `config.variables` to be undefined in those environments and don't want that to be treated as an error.
> 
> Maybe we could make it so that variable validation only occurs if `config.variables` exists?

@rpaul-stripe this validation is only checking that the variables object has the property, not if the value is correct, so even if we keep this PR as is I believe it will still work. 

Though I am totally peaceful with only validating if `config.variables`.

**Comment by mfix-stripe** [comment]
@rpaul-stripe just updated this to only validate if `config.variables` exists—PTAL

**Review by segphault — APPROVED** [review]
Thanks!

**Review by rpaul-stripe — APPROVED** [review]

**Pull request merged**
